export default {
	THEME_CHANGE:'THEME_CHANGE',
	THEME_INIT:'THEME_INIT',
	POPULAR_REFRESH:'POPULAR_REFRESH',	//刷新
	POPULAR_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',	//下拉刷新失败
	POPULAR_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',	//下拉刷新成功
	POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',	// 上拉加载更多成功
	POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',	// 上拉加载更多失败
}