export default {
	THEME_CHANGE:'THEME_CHANGE',
	THEME_INIT:'THEME_INIT',
	POPULAR_REFRESH:'POPULAR_REFRESH',	//刷新
	POPULAR_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',	//下拉刷新失败
	POPULAR_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',	//下拉刷新成功
	POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',	// 上拉加载更多成功
	POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',	// 上拉加载更多失败
	FLUSH_POPULAR_FAVORITE: "FLUSH_POPULAR_FAVORITE",	//最热收藏更新
	TRENDING_FLUSH_FAVORITE: "TRENDING_FLUSH_FAVORITE",	//趋势收藏更新
	TRENDING_REFRESH:'TRENDING_REFRESH',	//趋势页刷新
	TRENDING_REFRESH_FAIL:'TRENDING_REFRESH_FAIL',	//趋势页下拉刷新失败
	TRENDING_REFRESH_SUCCESS:'TRENDING_REFRESH_SUCCESS',	//趋势页下拉刷新成功
	TRENDING_LOAD_MORE_SUCCESS:'TRENDING_LOAD_MORE_SUCCESS',	// 趋势页上拉加载更多成功
	TRENDING_LOAD_MORE_FAIL:'TRENDING_LOAD_MORE_FAIL',	// 趋势页上拉加载更多失败
	FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",	//获取收藏数据
	FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",	//收藏成功
	FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",	//收藏失败
	LANGUAGE_LOAD_SUCCESS:'LANGUAGE_LOAD_SUCCESS',	//加载标签
}